// AUTO-GENERATED by scripts/generate-item-types.ts — do not edit manually
// Run: bun run generate:types

export interface CreatorBase<T extends string = string> {
  creatorType: T;
  firstName?: string | undefined;
  lastName?: string | undefined;
  name?: string | undefined;
}

export type ArtworkCreatorType = "artist" | "contributor";
export type AudioRecordingCreatorType = "performer" | "composer" | "contributor" | "originalCreator" | "translator" | "wordsBy";
export type BillCreatorType = "sponsor" | "contributor" | "cosponsor";
export type BlogPostCreatorType = "author" | "commenter" | "contributor" | "translator";
export type BookCreatorType = "author" | "contributor" | "editor" | "seriesEditor" | "translator";
export type BookSectionCreatorType = "author" | "bookAuthor" | "contributor" | "editor" | "seriesEditor" | "translator";
export type CaseCreatorType = "author" | "contributor" | "counsel";
export type ConferencePaperCreatorType = "author" | "contributor" | "editor" | "seriesEditor" | "translator";
export type DatasetCreatorType = "author" | "contributor";
export type DictionaryEntryCreatorType = "author" | "contributor" | "editor" | "seriesEditor" | "translator";
export type DocumentCreatorType = "author" | "contributor" | "editor" | "reviewedAuthor" | "translator";
export type EmailCreatorType = "author" | "contributor" | "recipient" | "translator";
export type EncyclopediaArticleCreatorType = "author" | "contributor" | "editor" | "seriesEditor" | "translator";
export type FilmCreatorType = "director" | "castMember" | "contributor" | "guest" | "host" | "narrator" | "producer" | "scriptwriter" | "translator";
export type ForumPostCreatorType = "author" | "contributor";
export type HearingCreatorType = "contributor";
export type InstantMessageCreatorType = "author" | "contributor" | "recipient";
export type InterviewCreatorType = "interviewee" | "contributor" | "interviewer" | "translator";
export type JournalArticleCreatorType = "author" | "contributor" | "editor" | "reviewedAuthor" | "translator";
export type LetterCreatorType = "author" | "contributor" | "recipient" | "translator";
export type MagazineArticleCreatorType = "author" | "contributor" | "reviewedAuthor" | "translator";
export type ManuscriptCreatorType = "author" | "contributor" | "translator";
export type MapCreatorType = "cartographer" | "contributor" | "seriesEditor";
export type NewspaperArticleCreatorType = "author" | "contributor" | "reviewedAuthor" | "translator";
export type PatentCreatorType = "inventor" | "attorneyAgent" | "contributor";
export type PodcastCreatorType = "podcaster" | "castMember" | "contributor" | "director" | "executiveProducer" | "guest" | "producer" | "scriptwriter" | "seriesCreator" | "translator";
export type PreprintCreatorType = "author" | "contributor" | "editor" | "reviewedAuthor" | "translator";
export type PresentationCreatorType = "presenter" | "chair" | "contributor" | "organizer" | "translator";
export type RadioBroadcastCreatorType = "creator" | "castMember" | "contributor" | "director" | "executiveProducer" | "guest" | "host" | "producer" | "scriptwriter" | "seriesCreator" | "translator";
export type ReportCreatorType = "author" | "contributor" | "editor" | "seriesEditor" | "translator";
export type ComputerProgramCreatorType = "programmer" | "contributor";
export type StandardCreatorType = "author" | "contributor" | "editor";
export type StatuteCreatorType = "author" | "contributor";
export type TvBroadcastCreatorType = "director" | "castMember" | "contributor" | "executiveProducer" | "guest" | "host" | "narrator" | "producer" | "scriptwriter" | "seriesCreator" | "translator";
export type ThesisCreatorType = "author" | "contributor";
export type VideoRecordingCreatorType = "creator" | "castMember" | "contributor" | "director" | "executiveProducer" | "guest" | "host" | "narrator" | "producer" | "scriptwriter" | "translator";
export type WebpageCreatorType = "author" | "contributor" | "translator";
