// AUTO-GENERATED by scripts/generate-item-types.ts — do not edit manually
// Run: bun run generate:types

import type { ItemBase } from "./common.js";
import type {
  CreatorBase,
  ArtworkCreatorType,
  AudioRecordingCreatorType,
  BillCreatorType,
  BlogPostCreatorType,
  BookCreatorType,
  BookSectionCreatorType,
  CaseCreatorType,
  ConferencePaperCreatorType,
  DatasetCreatorType,
  DictionaryEntryCreatorType,
  DocumentCreatorType,
  EmailCreatorType,
  EncyclopediaArticleCreatorType,
  FilmCreatorType,
  ForumPostCreatorType,
  HearingCreatorType,
  InstantMessageCreatorType,
  InterviewCreatorType,
  JournalArticleCreatorType,
  LetterCreatorType,
  MagazineArticleCreatorType,
  ManuscriptCreatorType,
  MapCreatorType,
  NewspaperArticleCreatorType,
  PatentCreatorType,
  PodcastCreatorType,
  PreprintCreatorType,
  PresentationCreatorType,
  RadioBroadcastCreatorType,
  ReportCreatorType,
  ComputerProgramCreatorType,
  StandardCreatorType,
  StatuteCreatorType,
  TvBroadcastCreatorType,
  ThesisCreatorType,
  VideoRecordingCreatorType,
  WebpageCreatorType,
} from "./creators.js";

/** Artwork */
export interface ArtworkItemData extends ItemBase {
  itemType: "artwork";
  creators: ReadonlyArray<CreatorBase<ArtworkCreatorType>>;
  title: string;
  abstractNote: string;
  artworkMedium: string;
  artworkSize: string;
  date: string;
  eventPlace: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  archive: string;
  archiveLocation: string;
  shortTitle: string;
  language: string;
  libraryCatalog: string;
  callNumber: string;
  rights: string;
  extra: string;
}

/** Audio Recording */
export interface AudioRecordingItemData extends ItemBase {
  itemType: "audioRecording";
  creators: ReadonlyArray<CreatorBase<AudioRecordingCreatorType>>;
  title: string;
  abstractNote: string;
  audioRecordingFormat: string;
  seriesTitle: string;
  volume: string;
  numberOfVolumes: string;
  label: string;
  place: string;
  date: string;
  runningTime: string;
  ISBN: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  archive: string;
  archiveLocation: string;
  shortTitle: string;
  language: string;
  libraryCatalog: string;
  callNumber: string;
  rights: string;
  extra: string;
}

/** Bill */
export interface BillItemData extends ItemBase {
  itemType: "bill";
  creators: ReadonlyArray<CreatorBase<BillCreatorType>>;
  title: string;
  abstractNote: string;
  billNumber: string;
  code: string;
  codeVolume: string;
  section: string;
  codePages: string;
  legislativeBody: string;
  session: string;
  history: string;
  date: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  shortTitle: string;
  language: string;
  rights: string;
  extra: string;
}

/** Blog Post */
export interface BlogPostItemData extends ItemBase {
  itemType: "blogPost";
  creators: ReadonlyArray<CreatorBase<BlogPostCreatorType>>;
  title: string;
  abstractNote: string;
  blogTitle: string;
  websiteType: string;
  date: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  ISSN: string;
  shortTitle: string;
  language: string;
  rights: string;
  extra: string;
}

/** Book */
export interface BookItemData extends ItemBase {
  itemType: "book";
  creators: ReadonlyArray<CreatorBase<BookCreatorType>>;
  title: string;
  abstractNote: string;
  series: string;
  seriesNumber: string;
  volume: string;
  numberOfVolumes: string;
  edition: string;
  date: string;
  publisher: string;
  place: string;
  originalDate: string;
  originalPublisher: string;
  originalPlace: string;
  format: string;
  numPages: string;
  ISBN: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  ISSN: string;
  archive: string;
  archiveLocation: string;
  shortTitle: string;
  language: string;
  libraryCatalog: string;
  callNumber: string;
  rights: string;
  extra: string;
}

/** Book Section */
export interface BookSectionItemData extends ItemBase {
  itemType: "bookSection";
  creators: ReadonlyArray<CreatorBase<BookSectionCreatorType>>;
  title: string;
  abstractNote: string;
  bookTitle: string;
  series: string;
  seriesNumber: string;
  volume: string;
  numberOfVolumes: string;
  edition: string;
  date: string;
  publisher: string;
  place: string;
  originalDate: string;
  originalPublisher: string;
  originalPlace: string;
  format: string;
  pages: string;
  ISBN: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  ISSN: string;
  archive: string;
  archiveLocation: string;
  shortTitle: string;
  language: string;
  libraryCatalog: string;
  callNumber: string;
  rights: string;
  extra: string;
}

/** Case */
export interface CaseItemData extends ItemBase {
  itemType: "case";
  creators: ReadonlyArray<CreatorBase<CaseCreatorType>>;
  caseName: string;
  abstractNote: string;
  court: string;
  dateDecided: string;
  docketNumber: string;
  reporter: string;
  reporterVolume: string;
  firstPage: string;
  history: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  shortTitle: string;
  language: string;
  rights: string;
  extra: string;
}

/** Conference Paper */
export interface ConferencePaperItemData extends ItemBase {
  itemType: "conferencePaper";
  creators: ReadonlyArray<CreatorBase<ConferencePaperCreatorType>>;
  title: string;
  abstractNote: string;
  proceedingsTitle: string;
  conferenceName: string;
  publisher: string;
  place: string;
  date: string;
  eventPlace: string;
  volume: string;
  issue: string;
  numberOfVolumes: string;
  pages: string;
  series: string;
  seriesNumber: string;
  DOI: string;
  ISBN: string;
  citationKey: string;
  url: string;
  accessDate: string;
  ISSN: string;
  archive: string;
  archiveLocation: string;
  shortTitle: string;
  language: string;
  libraryCatalog: string;
  callNumber: string;
  rights: string;
  extra: string;
}

/** Dataset */
export interface DatasetItemData extends ItemBase {
  itemType: "dataset";
  creators: ReadonlyArray<CreatorBase<DatasetCreatorType>>;
  title: string;
  abstractNote: string;
  identifier: string;
  type: string;
  versionNumber: string;
  date: string;
  repository: string;
  repositoryLocation: string;
  format: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  archive: string;
  archiveLocation: string;
  shortTitle: string;
  language: string;
  libraryCatalog: string;
  callNumber: string;
  rights: string;
  extra: string;
}

/** Dictionary Entry */
export interface DictionaryEntryItemData extends ItemBase {
  itemType: "dictionaryEntry";
  creators: ReadonlyArray<CreatorBase<DictionaryEntryCreatorType>>;
  title: string;
  abstractNote: string;
  dictionaryTitle: string;
  series: string;
  seriesNumber: string;
  volume: string;
  numberOfVolumes: string;
  edition: string;
  date: string;
  publisher: string;
  place: string;
  pages: string;
  ISBN: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  archive: string;
  archiveLocation: string;
  shortTitle: string;
  language: string;
  libraryCatalog: string;
  callNumber: string;
  rights: string;
  extra: string;
}

/** Document */
export interface DocumentItemData extends ItemBase {
  itemType: "document";
  creators: ReadonlyArray<CreatorBase<DocumentCreatorType>>;
  title: string;
  abstractNote: string;
  type: string;
  date: string;
  publisher: string;
  place: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  archive: string;
  archiveLocation: string;
  shortTitle: string;
  language: string;
  libraryCatalog: string;
  callNumber: string;
  rights: string;
  extra: string;
}

/** E-mail */
export interface EmailItemData extends ItemBase {
  itemType: "email";
  creators: ReadonlyArray<CreatorBase<EmailCreatorType>>;
  subject: string;
  abstractNote: string;
  date: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  shortTitle: string;
  language: string;
  rights: string;
  extra: string;
}

/** Encyclopedia Article */
export interface EncyclopediaArticleItemData extends ItemBase {
  itemType: "encyclopediaArticle";
  creators: ReadonlyArray<CreatorBase<EncyclopediaArticleCreatorType>>;
  title: string;
  abstractNote: string;
  encyclopediaTitle: string;
  series: string;
  seriesNumber: string;
  volume: string;
  numberOfVolumes: string;
  edition: string;
  date: string;
  publisher: string;
  place: string;
  pages: string;
  ISBN: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  archive: string;
  archiveLocation: string;
  shortTitle: string;
  language: string;
  libraryCatalog: string;
  callNumber: string;
  rights: string;
  extra: string;
}

/** Film */
export interface FilmItemData extends ItemBase {
  itemType: "film";
  creators: ReadonlyArray<CreatorBase<FilmCreatorType>>;
  title: string;
  abstractNote: string;
  distributor: string;
  place: string;
  date: string;
  genre: string;
  videoRecordingFormat: string;
  runningTime: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  archive: string;
  archiveLocation: string;
  shortTitle: string;
  language: string;
  libraryCatalog: string;
  callNumber: string;
  rights: string;
  extra: string;
}

/** Forum Post */
export interface ForumPostItemData extends ItemBase {
  itemType: "forumPost";
  creators: ReadonlyArray<CreatorBase<ForumPostCreatorType>>;
  title: string;
  abstractNote: string;
  forumTitle: string;
  postType: string;
  date: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  shortTitle: string;
  language: string;
  rights: string;
  extra: string;
}

/** Hearing */
export interface HearingItemData extends ItemBase {
  itemType: "hearing";
  creators: ReadonlyArray<CreatorBase<HearingCreatorType>>;
  title: string;
  abstractNote: string;
  committee: string;
  publisher: string;
  numberOfVolumes: string;
  documentNumber: string;
  pages: string;
  legislativeBody: string;
  session: string;
  history: string;
  date: string;
  place: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  shortTitle: string;
  language: string;
  rights: string;
  extra: string;
}

/** Instant Message */
export interface InstantMessageItemData extends ItemBase {
  itemType: "instantMessage";
  creators: ReadonlyArray<CreatorBase<InstantMessageCreatorType>>;
  title: string;
  abstractNote: string;
  date: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  shortTitle: string;
  language: string;
  rights: string;
  extra: string;
}

/** Interview */
export interface InterviewItemData extends ItemBase {
  itemType: "interview";
  creators: ReadonlyArray<CreatorBase<InterviewCreatorType>>;
  title: string;
  abstractNote: string;
  interviewMedium: string;
  date: string;
  publisher: string;
  place: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  archive: string;
  archiveLocation: string;
  shortTitle: string;
  language: string;
  libraryCatalog: string;
  callNumber: string;
  rights: string;
  extra: string;
}

/** Journal Article */
export interface JournalArticleItemData extends ItemBase {
  itemType: "journalArticle";
  creators: ReadonlyArray<CreatorBase<JournalArticleCreatorType>>;
  title: string;
  abstractNote: string;
  publicationTitle: string;
  publisher: string;
  place: string;
  date: string;
  volume: string;
  issue: string;
  section: string;
  partNumber: string;
  partTitle: string;
  pages: string;
  series: string;
  seriesTitle: string;
  seriesText: string;
  journalAbbreviation: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  PMID: string;
  PMCID: string;
  ISSN: string;
  archive: string;
  archiveLocation: string;
  shortTitle: string;
  language: string;
  libraryCatalog: string;
  callNumber: string;
  rights: string;
  extra: string;
}

/** Letter */
export interface LetterItemData extends ItemBase {
  itemType: "letter";
  creators: ReadonlyArray<CreatorBase<LetterCreatorType>>;
  title: string;
  abstractNote: string;
  letterType: string;
  date: string;
  eventPlace: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  archive: string;
  archiveLocation: string;
  shortTitle: string;
  language: string;
  libraryCatalog: string;
  callNumber: string;
  rights: string;
  extra: string;
}

/** Magazine Article */
export interface MagazineArticleItemData extends ItemBase {
  itemType: "magazineArticle";
  creators: ReadonlyArray<CreatorBase<MagazineArticleCreatorType>>;
  title: string;
  abstractNote: string;
  publicationTitle: string;
  publisher: string;
  place: string;
  date: string;
  volume: string;
  issue: string;
  pages: string;
  ISSN: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  archive: string;
  archiveLocation: string;
  shortTitle: string;
  language: string;
  libraryCatalog: string;
  callNumber: string;
  rights: string;
  extra: string;
}

/** Manuscript */
export interface ManuscriptItemData extends ItemBase {
  itemType: "manuscript";
  creators: ReadonlyArray<CreatorBase<ManuscriptCreatorType>>;
  title: string;
  abstractNote: string;
  manuscriptType: string;
  institution: string;
  place: string;
  date: string;
  numPages: string;
  number: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  archive: string;
  archiveLocation: string;
  shortTitle: string;
  language: string;
  libraryCatalog: string;
  callNumber: string;
  rights: string;
  extra: string;
}

/** Map */
export interface MapItemData extends ItemBase {
  itemType: "map";
  creators: ReadonlyArray<CreatorBase<MapCreatorType>>;
  title: string;
  abstractNote: string;
  mapType: string;
  scale: string;
  seriesTitle: string;
  edition: string;
  publisher: string;
  place: string;
  date: string;
  DOI: string;
  ISBN: string;
  citationKey: string;
  url: string;
  accessDate: string;
  archive: string;
  archiveLocation: string;
  shortTitle: string;
  language: string;
  libraryCatalog: string;
  callNumber: string;
  rights: string;
  extra: string;
}

/** Newspaper Article */
export interface NewspaperArticleItemData extends ItemBase {
  itemType: "newspaperArticle";
  creators: ReadonlyArray<CreatorBase<NewspaperArticleCreatorType>>;
  title: string;
  abstractNote: string;
  publicationTitle: string;
  publisher: string;
  place: string;
  date: string;
  volume: string;
  issue: string;
  edition: string;
  section: string;
  pages: string;
  ISSN: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  archive: string;
  archiveLocation: string;
  shortTitle: string;
  language: string;
  libraryCatalog: string;
  callNumber: string;
  rights: string;
  extra: string;
}

/** Patent */
export interface PatentItemData extends ItemBase {
  itemType: "patent";
  creators: ReadonlyArray<CreatorBase<PatentCreatorType>>;
  title: string;
  abstractNote: string;
  place: string;
  country: string;
  assignee: string;
  issuingAuthority: string;
  patentNumber: string;
  filingDate: string;
  pages: string;
  applicationNumber: string;
  priorityNumbers: string;
  issueDate: string;
  priorityDate: string;
  references: string;
  legalStatus: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  shortTitle: string;
  language: string;
  rights: string;
  extra: string;
}

/** Podcast */
export interface PodcastItemData extends ItemBase {
  itemType: "podcast";
  creators: ReadonlyArray<CreatorBase<PodcastCreatorType>>;
  title: string;
  abstractNote: string;
  seriesTitle: string;
  episodeNumber: string;
  audioFileType: string;
  date: string;
  publisher: string;
  place: string;
  runningTime: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  shortTitle: string;
  language: string;
  rights: string;
  extra: string;
}

/** Preprint */
export interface PreprintItemData extends ItemBase {
  itemType: "preprint";
  creators: ReadonlyArray<CreatorBase<PreprintCreatorType>>;
  title: string;
  abstractNote: string;
  genre: string;
  repository: string;
  archiveID: string;
  place: string;
  date: string;
  series: string;
  seriesNumber: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  archive: string;
  archiveLocation: string;
  shortTitle: string;
  language: string;
  libraryCatalog: string;
  callNumber: string;
  rights: string;
  extra: string;
}

/** Presentation */
export interface PresentationItemData extends ItemBase {
  itemType: "presentation";
  creators: ReadonlyArray<CreatorBase<PresentationCreatorType>>;
  title: string;
  abstractNote: string;
  presentationType: string;
  date: string;
  meetingName: string;
  place: string;
  series: string;
  sessionTitle: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  shortTitle: string;
  language: string;
  rights: string;
  extra: string;
}

/** Radio Broadcast */
export interface RadioBroadcastItemData extends ItemBase {
  itemType: "radioBroadcast";
  creators: ReadonlyArray<CreatorBase<RadioBroadcastCreatorType>>;
  title: string;
  abstractNote: string;
  programTitle: string;
  episodeNumber: string;
  audioRecordingFormat: string;
  network: string;
  place: string;
  date: string;
  runningTime: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  archive: string;
  archiveLocation: string;
  shortTitle: string;
  language: string;
  libraryCatalog: string;
  callNumber: string;
  rights: string;
  extra: string;
}

/** Report */
export interface ReportItemData extends ItemBase {
  itemType: "report";
  creators: ReadonlyArray<CreatorBase<ReportCreatorType>>;
  title: string;
  abstractNote: string;
  reportNumber: string;
  reportType: string;
  institution: string;
  place: string;
  date: string;
  seriesTitle: string;
  seriesNumber: string;
  pages: string;
  DOI: string;
  ISBN: string;
  citationKey: string;
  url: string;
  accessDate: string;
  ISSN: string;
  archive: string;
  archiveLocation: string;
  shortTitle: string;
  language: string;
  libraryCatalog: string;
  callNumber: string;
  rights: string;
  extra: string;
}

/** Software */
export interface ComputerProgramItemData extends ItemBase {
  itemType: "computerProgram";
  creators: ReadonlyArray<CreatorBase<ComputerProgramCreatorType>>;
  title: string;
  abstractNote: string;
  seriesTitle: string;
  versionNumber: string;
  date: string;
  system: string;
  company: string;
  place: string;
  programmingLanguage: string;
  rights: string;
  citationKey: string;
  url: string;
  accessDate: string;
  DOI: string;
  ISBN: string;
  archive: string;
  archiveLocation: string;
  libraryCatalog: string;
  callNumber: string;
  shortTitle: string;
  extra: string;
}

/** Standard */
export interface StandardItemData extends ItemBase {
  itemType: "standard";
  creators: ReadonlyArray<CreatorBase<StandardCreatorType>>;
  title: string;
  abstractNote: string;
  organization: string;
  committee: string;
  type: string;
  number: string;
  versionNumber: string;
  edition: string;
  status: string;
  date: string;
  publisher: string;
  place: string;
  partNumber: string;
  partTitle: string;
  ISBN: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  archive: string;
  archiveLocation: string;
  shortTitle: string;
  numPages: string;
  language: string;
  libraryCatalog: string;
  callNumber: string;
  rights: string;
  extra: string;
}

/** Statute */
export interface StatuteItemData extends ItemBase {
  itemType: "statute";
  creators: ReadonlyArray<CreatorBase<StatuteCreatorType>>;
  nameOfAct: string;
  abstractNote: string;
  code: string;
  codeNumber: string;
  publicLawNumber: string;
  dateEnacted: string;
  pages: string;
  section: string;
  session: string;
  history: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  shortTitle: string;
  language: string;
  rights: string;
  extra: string;
}

/** TV Broadcast */
export interface TvBroadcastItemData extends ItemBase {
  itemType: "tvBroadcast";
  creators: ReadonlyArray<CreatorBase<TvBroadcastCreatorType>>;
  title: string;
  abstractNote: string;
  programTitle: string;
  episodeNumber: string;
  videoRecordingFormat: string;
  network: string;
  place: string;
  date: string;
  runningTime: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  archive: string;
  archiveLocation: string;
  shortTitle: string;
  language: string;
  libraryCatalog: string;
  callNumber: string;
  rights: string;
  extra: string;
}

/** Thesis */
export interface ThesisItemData extends ItemBase {
  itemType: "thesis";
  creators: ReadonlyArray<CreatorBase<ThesisCreatorType>>;
  title: string;
  abstractNote: string;
  thesisType: string;
  university: string;
  place: string;
  date: string;
  series: string;
  seriesNumber: string;
  numPages: string;
  DOI: string;
  ISBN: string;
  citationKey: string;
  url: string;
  accessDate: string;
  ISSN: string;
  archive: string;
  archiveLocation: string;
  shortTitle: string;
  language: string;
  libraryCatalog: string;
  callNumber: string;
  rights: string;
  extra: string;
}

/** Video Recording */
export interface VideoRecordingItemData extends ItemBase {
  itemType: "videoRecording";
  creators: ReadonlyArray<CreatorBase<VideoRecordingCreatorType>>;
  title: string;
  abstractNote: string;
  videoRecordingFormat: string;
  seriesTitle: string;
  volume: string;
  numberOfVolumes: string;
  studio: string;
  place: string;
  date: string;
  runningTime: string;
  ISBN: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  archive: string;
  archiveLocation: string;
  shortTitle: string;
  language: string;
  libraryCatalog: string;
  callNumber: string;
  rights: string;
  extra: string;
}

/** Web Page */
export interface WebpageItemData extends ItemBase {
  itemType: "webpage";
  creators: ReadonlyArray<CreatorBase<WebpageCreatorType>>;
  title: string;
  abstractNote: string;
  websiteTitle: string;
  websiteType: string;
  date: string;
  publisher: string;
  place: string;
  DOI: string;
  citationKey: string;
  url: string;
  accessDate: string;
  shortTitle: string;
  language: string;
  rights: string;
  extra: string;
}

/** File/link attachment */
export interface AttachmentItemData extends ItemBase {
  itemType: "attachment";
  linkMode: string;
  title: string;
  accessDate: string;
  url: string;
  note: string;
  contentType: string;
  charset: string;
  filename: string;
  md5: string;
  mtime: number;
  parentItem: string;
}

/** Note */
export interface NoteItemData extends ItemBase {
  itemType: "note";
  note: string;
  parentItem: string;
}

/** Annotation */
export interface AnnotationItemData extends ItemBase {
  itemType: "annotation";
  annotationType: string;
  annotationText: string;
  annotationComment: string;
  annotationColor: string;
  annotationPageLabel: string;
  annotationSortIndex: string;
  annotationPosition: string;
  parentItem: string;
}

/** Discriminated union of all Zotero item types */
export type ItemData =
  | ArtworkItemData
  | AudioRecordingItemData
  | BillItemData
  | BlogPostItemData
  | BookItemData
  | BookSectionItemData
  | CaseItemData
  | ConferencePaperItemData
  | DatasetItemData
  | DictionaryEntryItemData
  | DocumentItemData
  | EmailItemData
  | EncyclopediaArticleItemData
  | FilmItemData
  | ForumPostItemData
  | HearingItemData
  | InstantMessageItemData
  | InterviewItemData
  | JournalArticleItemData
  | LetterItemData
  | MagazineArticleItemData
  | ManuscriptItemData
  | MapItemData
  | NewspaperArticleItemData
  | PatentItemData
  | PodcastItemData
  | PreprintItemData
  | PresentationItemData
  | RadioBroadcastItemData
  | ReportItemData
  | ComputerProgramItemData
  | StandardItemData
  | StatuteItemData
  | TvBroadcastItemData
  | ThesisItemData
  | VideoRecordingItemData
  | WebpageItemData
  | AttachmentItemData
  | NoteItemData
  | AnnotationItemData;

/** All valid item type strings */
export type ItemType = "artwork" | "audioRecording" | "bill" | "blogPost" | "book" | "bookSection" | "case" | "conferencePaper" | "dataset" | "dictionaryEntry" | "document" | "email" | "encyclopediaArticle" | "film" | "forumPost" | "hearing" | "instantMessage" | "interview" | "journalArticle" | "letter" | "magazineArticle" | "manuscript" | "map" | "newspaperArticle" | "patent" | "podcast" | "preprint" | "presentation" | "radioBroadcast" | "report" | "computerProgram" | "standard" | "statute" | "tvBroadcast" | "thesis" | "videoRecording" | "webpage" | "attachment" | "note" | "annotation";
