/**
 * Fetches Zotero schema from the API and generates TypeScript type definitions.
 * Produces:
 *   - packages/core/src/types/items.ts  (discriminated union of all item types)
 *   - packages/core/src/types/creators.ts (per-item-type creator type literals)
 *
 * Usage: bun run scripts/generate-item-types.ts
 */

const BASE_URL = "https://api.zotero.org";

interface ItemType {
  itemType: string;
  localized: string;
}

interface ItemField {
  field: string;
  localized: string;
}

interface CreatorType {
  creatorType: string;
  localized: string;
}

async function fetchJson<T>(path: string): Promise<T> {
  const res = await fetch(`${BASE_URL}${path}`);
  if (!res.ok) throw new Error(`GET ${path}: ${res.status} ${res.statusText}`);
  return res.json() as Promise<T>;
}

function pascalCase(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

async function main() {
  console.log("Fetching item types...");
  const itemTypes = await fetchJson<ItemType[]>("/itemTypes");

  // Skip "attachment", "note", "annotation" — they have special schemas
  const standardTypes = itemTypes.filter(
    (t) => !["attachment", "note", "annotation"].includes(t.itemType),
  );

  console.log(`Found ${standardTypes.length} standard item types`);

  // Fetch fields and creator types for each item type in parallel
  const typeData = await Promise.all(
    standardTypes.map(async (t) => {
      const [fields, creatorTypes] = await Promise.all([
        fetchJson<ItemField[]>(
          `/itemTypeFields?itemType=${encodeURIComponent(t.itemType)}`,
        ),
        fetchJson<CreatorType[]>(
          `/itemTypeCreatorTypes?itemType=${encodeURIComponent(t.itemType)}`,
        ),
      ]);
      return { itemType: t.itemType, localized: t.localized, fields, creatorTypes };
    }),
  );

  // --- Generate items.ts ---
  // Build creator type imports
  const creatorTypeImports = typeData
    .filter((td) => td.creatorTypes.length > 0)
    .map((td) => `  ${pascalCase(td.itemType)}CreatorType,`);

  const itemsLines: string[] = [
    "// AUTO-GENERATED by scripts/generate-item-types.ts — do not edit manually",
    '// Run: bun run generate:types',
    "",
    'import type { ItemBase } from "./common.js";',
    "import type {",
    "  CreatorBase,",
    ...creatorTypeImports,
    '} from "./creators.js";',
    "",
  ];

  // Collect all unique fields across all types (excluding 'itemType' and standard base fields)
  const baseFields = new Set([
    "itemType",
    "key",
    "version",
    "tags",
    "collections",
    "relations",
    "dateAdded",
    "dateModified",
    "creators",
  ]);

  for (const td of typeData) {
    const typeName = `${pascalCase(td.itemType)}ItemData`;
    const creatorTypeName = `${pascalCase(td.itemType)}CreatorType`;

    itemsLines.push(`/** ${td.localized} */`);
    itemsLines.push(`export interface ${typeName} extends ItemBase {`);
    itemsLines.push(`  itemType: "${td.itemType}";`);

    // Creators field with specific creator type
    if (td.creatorTypes.length > 0) {
      itemsLines.push(
        `  creators: ReadonlyArray<CreatorBase<${creatorTypeName}>>;`,
      );
    }

    // Item-specific fields
    for (const field of td.fields) {
      if (!baseFields.has(field.field)) {
        itemsLines.push(`  ${field.field}: string;`);
      }
    }

    itemsLines.push("}");
    itemsLines.push("");
  }

  // Attachment, Note, Annotation types (special)
  itemsLines.push("/** File/link attachment */");
  itemsLines.push("export interface AttachmentItemData extends ItemBase {");
  itemsLines.push('  itemType: "attachment";');
  itemsLines.push("  linkMode: string;");
  itemsLines.push("  title: string;");
  itemsLines.push("  accessDate: string;");
  itemsLines.push("  url: string;");
  itemsLines.push("  note: string;");
  itemsLines.push("  contentType: string;");
  itemsLines.push("  charset: string;");
  itemsLines.push("  filename: string;");
  itemsLines.push("  md5: string;");
  itemsLines.push("  mtime: number;");
  itemsLines.push("  parentItem: string;");
  itemsLines.push("}");
  itemsLines.push("");

  itemsLines.push("/** Note */");
  itemsLines.push("export interface NoteItemData extends ItemBase {");
  itemsLines.push('  itemType: "note";');
  itemsLines.push("  note: string;");
  itemsLines.push("  parentItem: string;");
  itemsLines.push("}");
  itemsLines.push("");

  itemsLines.push("/** Annotation */");
  itemsLines.push("export interface AnnotationItemData extends ItemBase {");
  itemsLines.push('  itemType: "annotation";');
  itemsLines.push("  annotationType: string;");
  itemsLines.push("  annotationText: string;");
  itemsLines.push("  annotationComment: string;");
  itemsLines.push("  annotationColor: string;");
  itemsLines.push("  annotationPageLabel: string;");
  itemsLines.push("  annotationSortIndex: string;");
  itemsLines.push("  annotationPosition: string;");
  itemsLines.push("  parentItem: string;");
  itemsLines.push("}");
  itemsLines.push("");

  // Discriminated union
  const allTypeNames = [
    ...typeData.map((td) => `${pascalCase(td.itemType)}ItemData`),
    "AttachmentItemData",
    "NoteItemData",
    "AnnotationItemData",
  ];

  itemsLines.push("/** Discriminated union of all Zotero item types */");
  itemsLines.push("export type ItemData =");
  for (let i = 0; i < allTypeNames.length; i++) {
    itemsLines.push(`  | ${allTypeNames[i]}${i === allTypeNames.length - 1 ? ";" : ""}`);
  }
  itemsLines.push("");

  // ItemType string literal union
  const allItemTypeStrings = [
    ...typeData.map((td) => `"${td.itemType}"`),
    '"attachment"',
    '"note"',
    '"annotation"',
  ];
  itemsLines.push("/** All valid item type strings */");
  itemsLines.push(
    `export type ItemType = ${allItemTypeStrings.join(" | ")};`,
  );
  itemsLines.push("");

  // --- Generate creators.ts ---
  const creatorsLines: string[] = [
    "// AUTO-GENERATED by scripts/generate-item-types.ts — do not edit manually",
    '// Run: bun run generate:types',
    "",
  ];

  // Generic creator base
  creatorsLines.push(
    "export interface CreatorBase<T extends string = string> {",
  );
  creatorsLines.push("  creatorType: T;");
  creatorsLines.push("  firstName?: string | undefined;");
  creatorsLines.push("  lastName?: string | undefined;");
  creatorsLines.push("  name?: string | undefined;");
  creatorsLines.push("}");
  creatorsLines.push("");

  // Per-item-type creator type literals
  for (const td of typeData) {
    if (td.creatorTypes.length === 0) continue;
    const typeName = `${pascalCase(td.itemType)}CreatorType`;
    const literals = td.creatorTypes.map((c) => `"${c.creatorType}"`).join(" | ");
    creatorsLines.push(`export type ${typeName} = ${literals};`);
  }
  creatorsLines.push("");

  // Write files
  const outDir = "packages/core/src/api/types";
  await Bun.write(`${outDir}/items.ts`, itemsLines.join("\n"));
  await Bun.write(`${outDir}/creators.ts`, creatorsLines.join("\n"));

  console.log(`Generated ${outDir}/items.ts (${allTypeNames.length} item types)`);
  console.log(`Generated ${outDir}/creators.ts`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
